---
- name: create /root/.ssh
  file: path=/root/.ssh state=directory

- name: copy {{ admin_username }} ssh key toward root
  copy:
    src: /root/.ssh/id_rsa.pub
    dest: /root/.ssh/authorized_keys
    owner: root
    group: root
    mode: 0644

- name: Register as user "{{ rhel_user }}" with password --REDACTED-- and auto-subscribe to pool "{{ rhel_pool }}"
  redhat_subscription:
    state: present
    username: "{{ rhel_user }}"
    password: "{{ rhel_pass }}"
    pool_ids: "{{ rhel_pool }}"

- name: Disable all RHSM repositories
  rhsm_repository:
    name: '*'
    state: disabled

- name: Use yum-config-manager to disable the remaining yum repositories
  shell: 'yum-config-manager --disable \*'

- name: Enable only the repositories required by OpenShift Container Platform {{ ose_version }}
  rhsm_repository:
    name: "{{ item }}"
    state: enabled
  with_items:
    - "rhel-7-server-rpms"
    - "rhel-7-server-extras-rpms"
    - "rhel-7-server-ose-{{ ose_version }}-rpms"
    - "rhel-7-fast-datapath-rpms"

- name: set SELinux to permissive
  selinux:
    policy: targeted
    state: permissive

- name: set SELinux to permissive in config
  lineinfile:
    path: /etc/selinux/config
    regexp: '^#SELINUX='
    line: 'SELINUX=permissive'

- name: set SELinuxType to targeted in config
  lineinfile:
    path: /etc/selinux/config
    regexp: '^#SELINUXTYPE='
    line: 'SELINUX=targeted'

- name: disable and stop firewalld in systemctl
  systemd:
    name: firewalld
    state: stopped
    enabled: False

- name: upgrade all packages
  yum:
    name: '*'
    state: latest

- name: Install pre-requisites ose-host_preparation
  yum: name={{ item }} state=present
  with_items:
   - wget
   - git
   - net-tools
   - bind-utils
   - iptables-services
   - bridge-utils
   - bash-completion
   - kexec-tools
   - sos
   - psacct

- name: Install Docker
  yum: name={{ item }} state=present
  with_items:
   - docker-1.12.6

- name: Enable and Start Docker in systemctl
  systemd:
    name: docker
    state: started
    enabled: True

- name: Install Atomic Openshift Utils
  yum: name={{ item }} state=present
  with_items:
   - atomic-openshift-utils

- name: create /root/nuage-docker
  file: path=/root/nuage-docker state=directory

- name: "Copy Nuage Software"
  copy:
    src: "{{ nuage_docker_basedir }}/{{ item }}"
    dest: "/root/nuage-docker/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - "{{ nuage_cni_image }}"
    - "{{ nuage_infra_image }}"
    - "{{ nuage_master_image }}"
    - "{{ nuage_vrs_image }}"
    - "{{ nuage_strongswan_image | default('') }}"
    - "{{ nuage_bootstrap_agent | default('') }}"

- name: Load Docker Nuage Software images
  docker_image:
    load_path: "/root/nuage-docker/{{ item }}"
    state: present
  with_items:
    - "{{ nuage_cni_image }}"
    - "{{ nuage_infra_image }}"
    - "{{ nuage_master_image }}"
    - "{{ nuage_vrs_image }}"
    - "{{ nuage_strongswan_image | default('') }}"
