---
- name: create /root/.ssh
  file: path=/root/.ssh state=directory

- name: copy {{ admin_username }} ssh key toward root
  copy:
    src: /root/.ssh/id_rsa.pub
    dest: /root/.ssh/authorized_keys
    owner: root
    group: root
    mode: 0644

- name: Register as user "{{ rhel_user }}" with password --REDACTED-- and auto-subscribe to pool "{{ rhel_pool }}"
  redhat_subscription:
    state: present
    username: "{{ rhel_user }}"
    password: "{{ rhel_pass }}"
    pool_ids: "{{ rhel_pool }}"

#- name: Disable all repos
#  shell: "yum-config-manager --disable \\\*"

- name: Enable only the repositories required by OpenShift Container Platform 3.7
  shell: subscription-manager repos --enable="rhel-7-server-rpms" --enable="rhel-7-server-extras-rpms" --enable="rhel-7-server-ose-3.7-rpms" --enable="rhel-7-fast-datapath-rpms"
- name: set SELinux to permissive
  selinux:
    policy: targeted
    state: permissive

- name: disable and stop firewalld in systemctl
  systemd:
    name: firewalld
    state: stopped
    enabled: False

- name: upgrade all packages
  yum:
    name: '*'
    state: latest

- name: Install pre-requisites ose-host_preparation
  yum: name={{ item }} state=present
  with_items:
   - wget
   - git
   - net-tools
   - bind-utils
   - iptables-services
   - bridge-utils
   - bash-completion
   - kexec-tools
   - sos
   - psacct
   - atomic-openshift-utils

- name: Install Docker
  yum: name={{ item }} state=present
  with_items:
   - docker-1.12.6

- name: Enable and Start Docker in systemctl
  systemd:
    name: docker
    state: started
    enabled: True

- name: create /root/nuage-docker
  file: path=/root/nuage-docker state=directory

- name: "copy {{ item }}"
  copy:
    src: "/data/nuage_software/5.2.1/unzip/openshift/docker/{{ item }}"
    dest: "/root/nuage-docker/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - nuage-cni-docker-5.2.1-6.tar
    - nuage-infra-docker-5.2.1-7.tar
    - nuage-master-docker-5.2.1-7.tar
    - nuage-vrs-docker-5.2.1-10.tar

- name: load docker images
  shell: "docker load -i /root/nuage-docker/{{ item }}"
  with_items:
    - nuage-cni-docker-5.2.1-6.tar
    - nuage-infra-docker-5.2.1-7.tar
    - nuage-master-docker-5.2.1-7.tar
    - nuage-vrs-docker-5.2.1-10.tar
