---
- name: Create Azure VM
  hosts: localhost
  connection: local
  tasks:
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: ose
      name: myTestVM
      vm_size: Standard_D2s_v3
      admin_username: azureuser
      ssh_password_enabled: false
      ssh_public_keys:
        - path: /home/azureuser/.ssh/authorized_keys
          key_data: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDEi1Yie7wY9O13MlEgYZ2CDa7rxXDOv+1tmQCIkmy5GY89FQF9ik4KVRTNkf4Y7lNkJMFTSkQ4UwF3f1GBm4zpQ9pTb9LOj7ZtTKG7qS8u6h98SBA0UdrIVkuF2TLltZp4BDopmBTwWHX52aL5zE9VLBzXEfNRdfo+ehHSicJMZMcJmG2rkvHO2h5C5VPuUodSTbW1G6z93NpcRkwJxlxRrkbhc18qTeaP9f8wETY8pBZqq9uesAKoqogUKq943mspj2msNL/atvjjGNzHR/8/YiLqC9Uyx+RFBnCfdjekye1D6fsvAzoaZz2ou5waYsI64EQDy2vcvdOe0eSeKzEMSEIF5j4ZSi9VsZBhXe+N+2r8ibPzkvFowf56VEDFhYh7nXQynk02XQAp58jwTSHUax7v/aA815Uqj7xc/AnW1LOLw7SUe1j31KL7YOn3tVz85lOZ6q3oGlQfF27aRzY9BZ14XKe2ayHmJtWb5QWLaz0mMCU+UA3Gdoodf4xzWqgPJTkJhIWcoHnSZI2ZCZF6SMRKbu+gAqnAOxXBMkhzH+RUJFpsuUa8IaPTaUC2ZLu+semwOYt2/8DEwUIzb2YKg6zOLKTg2u61unK7R9Qf7ZZrBeyxVzwj/o0cWmqS+Oezbf/em51ctBHahmhV6I3HrJQ+5Pe7LgJjLDleP8LcIw== hans.thienpondt@nokia.com"
      network_interfaces: myTestNIC
      image:
        offer: RHEL
        publisher: RedHat
        sku: '7-RAW'
        version: 7.4.2018010506
