---
- name: Create virtual network
  with_items: "{{ virtualnetwork }}"
  azure_rm_virtualnetwork:
    resource_group: "{{ resource_group }}"
    name: "{{ item.name }}"
    address_prefixes: "{{ item.cidr }}"
- name: Add subnets
  with_items: "{{ subnets }}"
  azure_rm_subnet:
    resource_group: "{{ resource_group }}"
    name: "{{ item.name }}"
    address_prefix: "{{ item.cidr }}"
    virtual_network: "{{ item.vnet }}"
